### ISSUE TITLE
Bug: Codecard svg distorted

### ISSUE THREAD

**Issue by lcscosta** [manexim/manexim.github.io#1]
Hi everybody,

Congratulations on the apps and organization. The site has a bug in the codecard probably caused by bootstrap. In my browser, I get:

![codecard-bug](https://user-images.githubusercontent.com/45444800/219254542-fb64382c-e075-41f9-ba3a-2967ac9d72ec.png)

Looking for a possible solution, maybe add the CSS property `object-fit: contain;` to element.

**Comment by meisenzahl** [comment]
Thank you very much for creating the issue and suggesting a solution. The bug has been fixed in cbefec1.
